// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThesisWork.Repository;

namespace ThesisWork.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210404153010_Test1")]
    partial class Test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThesisWork.Models.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Описание");

                    b.Property<string>("Qalification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Квалификация");

                    b.Property<int>("Граффик Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Граффик Id");

                    b.ToTable("Компетенции");
                });

            modelBuilder.Entity("ThesisWork.Models.Practice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Название практики");

                    b.Property<string>("PracticeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Тип практики");

                    b.Property<string>("PracticeView")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Вид практики");

                    b.Property<string>("Semestr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Семестр");

                    b.Property<int>("WeeksNumber")
                        .HasColumnType("int")
                        .HasColumnName("Кол-во недель");

                    b.HasKey("Id");

                    b.ToTable("Практики");
                });

            modelBuilder.Entity("ThesisWork.Models.PracticeSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id Графика практики")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EducationYear")
                        .HasColumnType("datetime2")
                        .HasColumnName("Уч. год");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата конца");

                    b.Property<int>("ExamenHours")
                        .HasColumnType("int")
                        .HasColumnName("Часы на зачёт");

                    b.Property<string>("GroupNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadFcs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ФИО Рук.Практики");

                    b.Property<int>("HoursClass")
                        .HasColumnType("int")
                        .HasColumnName("Аудиторные часы");

                    b.Property<int>("HoursSRS")
                        .HasColumnType("int")
                        .HasColumnName("Часы СРС");

                    b.Property<int>("Id Практики")
                        .HasColumnType("int");

                    b.Property<string>("SchedulePage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Лист");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата начала");

                    b.Property<int>("StudentsNumber")
                        .HasColumnType("int")
                        .HasColumnName("Кол-во студентов");

                    b.Property<string>("Vector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Направление");

                    b.Property<int>("WeeksNumber")
                        .HasColumnType("int")
                        .HasColumnName("Кол-во недель");

                    b.HasKey("Id");

                    b.HasIndex("Id Практики");

                    b.ToTable("График практик");
                });

            modelBuilder.Entity("ThesisWork.Models.Student", b =>
                {
                    b.Property<string>("GradeBookNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Номер зачётной книжки");

                    b.Property<int>("CourseNumber")
                        .HasColumnType("int")
                        .HasColumnName("Курс");

                    b.Property<string>("Departament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Отделение");

                    b.Property<string>("GroupNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Номер группы");

                    b.Property<bool>("Mentor")
                        .HasColumnType("bit")
                        .HasColumnName("Староста");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Имя");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Отчество");

                    b.Property<DateTime>("SudtingYear")
                        .HasColumnType("datetime2")
                        .HasColumnName("Уч. год");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Фамилия");

                    b.Property<string>("Vector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Направление");

                    b.HasKey("GradeBookNumber");

                    b.ToTable("Студенты");
                });

            modelBuilder.Entity("ThesisWork.Models.Teacher", b =>
                {
                    b.Property<int>("TabNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcademicDegree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Уч. степень");

                    b.Property<string>("FCs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ФИО");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Имя");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Пароль");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Отчество");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Контактный телефон");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Должность");

                    b.Property<string>("Rate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ставка");

                    b.Property<string>("StaffingLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Штатность");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Фамилия");

                    b.Property<string>("TeachersTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Звание");

                    b.HasKey("TabNumber");

                    b.ToTable("Преподаватели");
                });

            modelBuilder.Entity("ThesisWork.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FCs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ФИО");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Логин");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Имя");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Пароль");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Отчество");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Роль");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Фамилия");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ThesisWork.Models.Competence", b =>
                {
                    b.HasOne("ThesisWork.Models.PracticeSchedule", "ScheduleId")
                        .WithMany()
                        .HasForeignKey("Граффик Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleId");
                });

            modelBuilder.Entity("ThesisWork.Models.PracticeSchedule", b =>
                {
                    b.HasOne("ThesisWork.Models.Practice", "PracticeId")
                        .WithMany()
                        .HasForeignKey("Id Практики")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeId");
                });
#pragma warning restore 612, 618
        }
    }
}
